# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# find the dir of .bashrc file (resolv symlink)
# we could use ``_SOURCE=$(dirname $(readlink -f ${BASH_SOURCE[0]}))``, however, OSX's version of
# ``readlink`` does not support '-f' option.
_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$_SOURCE" ]; do
    _TARGET=$(readlink "$_SOURCE")
    if [[ "$_TARGET" == /* ]]; then
        _SOURCE="$_TARGET"
    else
        _SOURCE=$(dirname "$_SOURCE")/$_TARGET
    fi
done
_SOURCE_DIR=$(dirname "$_SOURCE")
unset _SOURCE _TARGET

source $_SOURCE_DIR/functions.sh
_OS=$(detect_os)

# bash settings
shopt -s histappend
export HISTSIZE=1000000
export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "

# populate PATH
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
# bin files shipped with this repo
append_to_path $(dirname $_SOURCE_DIR)/bin
# homebrew: coreutils bin path
prepend_to_path_if_exist /usr/local/opt/coreutils/libexec/gnubin
# homebrew: gnu-sed bin path
prepend_to_path_if_exist /usr/local/opt/gnu-sed/libexec/gnubin
append_to_path $HOME/bin
append_to_path $HOME/.local/bin

# golang settings
export GOPATH=$HOME/.go
append_to_path $GOPATH/bin
# go installs to /usr/local/go on linux
append_to_path_if_exist /usr/local/go/bin

# bash completions
# bash-completion@2 requires this
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
source_if_exist /etc/bash_completion
command -v brew > /dev/null && source_if_exist $(brew --prefix)/share/bash-completion/bash_completion
command -v brew > /dev/null && source_if_exist $(brew --prefix)/etc/profile.d/bash_completion.sh

# aliases
source_if_exist $_SOURCE_DIR/aliases
# env variables to export
source_if_exist $_SOURCE_DIR/exports

# goenv
source_if_exist $_SOURCE_DIR/goenv

# pyenv
if command -v pyenv >/dev/null; then
    export WORKON_HOME=$HOME/.venvs
    #export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
    eval "$(pyenv init -)"
    pyenv virtualenvwrapper_lazy
fi

# virtualenv wrapper
#if command -v virtualenvwrapper.sh >/dev/null; then
#    if command -v python3 >/dev/null; then
#        export VIRTUALENVWRAPPER_PYTHON=`command -v python3`
#    elif command -v python2 >/dev/null; then
#        export VIRTUALENVWRAPPER_PYTHON=`command -v python2`
#    fi
#    export WORKON_HOME=$HOME/.venvs
#    source_if_exist `command -v virtualenvwrapper.sh`
#fi

# PS1
[[ -n "$SSH_TTY" ]] && export _IS_REMOTE="-(ssh)"
[[ -n "$REMOTEHOST" ]] && export _IS_REMOTE="${IS_REMOTE}-(rsh)"
[[ -n "$STY" ]] && export _IS_SCREEN="-(screen)"
PROMPT_COMMAND_FILE=$_SOURCE_DIR/ps1.sh
_update_ps1() {
    PS1=$($PROMPT_COMMAND_FILE $?)
}
if [ -x "$PROMPT_COMMAND_FILE" ]; then
    PROMPT_COMMAND="_update_ps1"
fi

# unset variables
unset _SOURCE_DIR
unset _OS

export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

#source_if_exist ~/.docker/init2/hosts/work.home.init2.me/activate
source_if_exist ~/.docker/init2/hosts/zc.szo.natureself.site/activate
